### ISSUE TITLE
Subsystem Decomposition

### ISSUE THREAD

**Issue by ghost** [alikaangoksu/ceng396-software-engineering#5]
![subsystem](https://user-images.githubusercontent.com/48490125/56460130-7fb80c80-63a6-11e9-9564-d60bfe0c2dcb.jpeg)

**Comment by alikaangoksu** [comment]
![indir](https://user-images.githubusercontent.com/47613498/56460155-e0474980-63a6-11e9-900d-f49a7487285c.png)
